/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#FF6B35",
        "primary-container": "#e85520",
        "on-primary": "#ffffff",
        "on-primary-container": "#fffbff",
        "primary-fixed": "#ffdbd2",
        "primary-fixed-dim": "#ffb4a2",
        "on-primary-fixed": "#3c0800",
        "on-primary-fixed-variant": "#891f01",
        "secondary": "#4f6073",
        "on-secondary": "#ffffff",
        "secondary-container": "#d2e4fb",
        "on-secondary-container": "#556679",
        "secondary-fixed": "#d2e4fb",
        "secondary-fixed-dim": "#b7c8de",
        "on-secondary-fixed": "#0b1d2d",
        "on-secondary-fixed-variant": "#38485a",
        "tertiary": "#006574",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#008093",
        "on-tertiary-container": "#f8fdff",
        "tertiary-fixed": "#a4eeff",
        "tertiary-fixed-dim": "#69d5ec",
        "on-tertiary-fixed": "#001f25",
        "on-tertiary-fixed-variant": "#004e5a",
        "surface": "#faf9f7",
        "surface-dim": "#dadad8",
        "surface-bright": "#faf9f7",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f4f3f1",
        "surface-container": "#efeeec",
        "surface-container-high": "#e9e8e6",
        "surface-container-highest": "#e3e2e0",
        "surface-variant": "#e3e2e0",
        "on-surface": "#1a1c1b",
        "on-surface-variant": "#58413c",
        "inverse-surface": "#2f3130",
        "inverse-on-surface": "#f1f1ef",
        "inverse-primary": "#ffb4a2",
        "background": "#faf9f7",
        "on-background": "#1a1c1b",
        "outline": "#8c716a",
        "outline-variant": "#e0bfb8",
        "surface-tint": "#aa3617",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        "headline": ["Noto Serif KR", "serif"],
        "body": ["Pretendard", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "2xl": "0.75rem",
        "3xl": "1rem",
        "full": "9999px"
      }
    },
  },
  plugins: [],
}
